# -*- coding: utf-8 -*-
"""Customer_Spending_Behavior_Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThBTTiW_bn36DWtic4Gcs7d4wBo0GUhq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

# Fix the file path below to the correct location of your CSV file
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Projects/IBM Training Project/customer spending behavior prediction.csv')
df.head()

df.tail()

df.info()

df.describe()

# Checking total no. of null values in columns

df.isnull().sum()

df.duplicated().sum()

df['Gender'].value_counts()

df['ProductCategory'].value_counts()

# One-Hot Encoding for 'Gender' and 'ProductCategory'
df = df.replace({'Gender':{"Male": 0, "Female": 1,"Other":-1}})
df=df.replace({'ProductCategory':{'Electronics':1,'Home':2,'Fashion':3,'Beauty':4}})
df.head(15)

# Categorize SpendingScore into Spending segment by diving it into range and assign low or high
df["SpendingSegment"] = pd.cut(df["SpendingScore"],bins=[0, 70, 100],labels=["Low", "High"])

# Count segments
print("\nSpending Segment Distribution:\n", df["SpendingSegment"].value_counts())
df

df['SpendingSegment'].value_counts()

# Pie chart (Product category)
plt.figure(figsize=(6, 6))
df["ProductCategory"].value_counts().plot.pie(
    autopct="%1.1f%%")
plt.title("Distribution based on Product Category")
plt.show()

# Pie Chart (Spending Segments)
plt.figure(figsize=(12, 6))
df["SpendingSegment"].value_counts().plot.pie(
    autopct="%1.1f%%"
)
plt.title("Customer Spending Segments")
plt.show()

# Box Plots (Spending segment vs Annual income)
plt.figure(figsize=(12, 6))
sns.boxplot(x="SpendingSegment", y="AnnualIncome", data=df)
plt.title("Annual Income by Spending Segment")
plt.show()

# Scatter Plot (Income vs. Spending Score)

plt.figure(figsize=(10, 6))
sns.scatterplot(x="AnnualIncome", y="SpendingScore", hue="SpendingSegment", data=df, palette="viridis")
plt.title("Income vs. Spending Score")
plt.show()

# Bar Plot (Spending segment vs website visit per month)

plt.figure(figsize=(10, 6))
sns.barplot(x="SpendingSegment", y="WebsiteVisitsPerMonth", data=df, ci=None)
plt.title("Avg. Website Visits by Spending Segment")
plt.show()

# BAR PLOT (Gender vs Last Month Purchase)
plt.figure(figsize=(8, 6))
sns.barplot(x="Gender", y="PurchasedLastMonth", data=df)
plt.title("Last Month Purchase by Gender")
plt.show()

from sklearn.model_selection import train_test_split

# Remove 'ProductCategory' along with other columns from the feature set
x = df.drop(["CustomerID", "SpendingScore", "SpendingSegment", "ProductCategory"], axis=1)
y = df["SpendingSegment"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

from sklearn.preprocessing import MinMaxScaler

# Scale numerical features
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

print("\nData After Scaling:\n", df.head())

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score,confusion_matrix

lr = LogisticRegression(max_iter=10000)
lr.fit(x_train, y_train)
y_pred_lr_train = lr.predict(x_train)
y_pred_lr_test = lr.predict(x_test)

print("Logistic Regression Accuracy for train:", accuracy_score(y_train, y_pred_lr_train))
print("Logistic Regression Accuracy for test:", accuracy_score(y_test, y_pred_lr_test))

print("\nClassification Report for testing:\n", classification_report(y_test, y_pred_lr_test))
print("\nClassification Report for training:\n", classification_report(y_train, y_pred_lr_train))

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score

dt = DecisionTreeClassifier(criterion='entropy',max_leaf_nodes=16,random_state=0)
dt.fit(x_train, y_train)
y_pred_dt_test = dt.predict(x_test)
y_pred_dt_train = dt.predict(x_train)

print("Decision Tree Accuracy for train:", accuracy_score(y_train, y_pred_dt_train))
print("Decision Tree Accuracy for test:", accuracy_score(y_test, y_pred_dt_test))


print("\nClassification Report for testing:\n", classification_report(y_test, y_pred_dt_test))
print("\nClassification Report for trainig:\n", classification_report(y_train, y_pred_dt_train))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(criterion='entropy',random_state=50)
rf.fit(x_train, y_train)
y_pred_rf_test = rf.predict(x_test)
y_pred_rf_train = rf.predict(x_train)

print("Random Forest Accuracy for train:", accuracy_score(y_train, y_pred_rf_train))
print("Random Forest Accuracy for test:", accuracy_score(y_test, y_pred_rf_test))

print("\nClassification Report for testing:\n", classification_report(y_test, y_pred_rf_test))
print("\nClassification Report for training:\n", classification_report(y_train, y_pred_rf_train))

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
y_pred_knn_test = knn.predict(x_test)
y_pred_knn_train = knn.predict(x_train)

print("KNN Accuracy for train:", accuracy_score(y_train, y_pred_knn_train))
print("KNN Accuracy for test:", accuracy_score(y_test, y_pred_knn_test))

print("\nClassification Report for testing:\n", classification_report(y_test, y_pred_knn_test))
print("\nClassification Report for training:\n", classification_report(y_train, y_pred_knn_train))

models_test = {
    "Logistic Regression": accuracy_score(y_test, y_pred_lr_test),
    "Decision Tree": accuracy_score(y_test, y_pred_dt_test),
    "Random Forest": accuracy_score(y_test, y_pred_rf_test),
    "KNN": accuracy_score(y_test, y_pred_knn_test)
}
models_train={
    "Logistic Regression": accuracy_score(y_train, y_pred_lr_train),
    "Decision Tree": accuracy_score(y_train, y_pred_dt_train),
    "Random Forest": accuracy_score(y_train, y_pred_rf_train),
    "KNN": accuracy_score(y_train, y_pred_knn_train)
}

best_model_test = max(models_test, key=models_test.get)
best_model_train = max(models_train, key=models_train.get)
print("\nBest Model for testing:", best_model_test, "with Accuracy:", models_test[best_model_test])
print("\nBest Model for training:", best_model_train, "with Accuracy:", models_train[best_model_train])

train_cm=confusion_matrix(y_train,y_pred_rf_train)
test_cm=confusion_matrix(y_test,y_pred_rf_test)
print(train_cm)
print(test_cm)
sns.heatmap(train_cm,annot=True,fmt='d')
plt.title('Train Confusion Matrix')
plt.show()

sns.heatmap(test_cm,annot=True,fmt='d')
plt.title('Test Confusion Matrix')
plt.show()